@extends('layouts.theme')

@section('content')
    <h1>salooh</h1>
    <h1>salooh</h1>
    <h1>salooh</h1>
    <h1>salooh</h1>
    <h1>salooh</h1>
    <h1>salooh</h1>
    <h1>salooh</h1>
    <h1>salooh</h1>
    <h1>salooh</h1>
    <h1>salooh</h1>
    <h1>salooh</h1>
    <h1>salooh</h1>
    <h1>salooh</h1>
    <h1>salooh</h1>
    <h1>salooh</h1>
    <h1>salooh</h1>
    <h1>salooh</h1>
    <h1>salooh</h1>
    <h1>salooh</h1>
    <h1>salooh</h1>
    <h1>salooh</h1>
    <h1>salooh</h1>
    <h1>salooh</h1>
    <h1>salooh</h1>
    <h1>salooh</h1>
    <h1>salooh</h1>
    <h1>salooh</h1>
    <h1>salooh</h1>
    <h1>salooh</h1>
    <h1>salooh</h1>
    <h1>salooh</h1>
    <h1>salooh</h1>
    <h1>salooh</h1>
    <h1>salooh</h1>
    <h1>salooh</h1>
    <h1>salooh</h1>
    <h1>salooh</h1>
    <h1>salooh</h1>
    <h1>salooh</h1>
    <h1>salooh</h1>
    <h1>salooh</h1>
    <h1>salooh</h1>
    <h1>salooh</h1>
    <h1>salooh</h1>
    <h1>salooh</h1>
    <h1>salooh</h1>
    <h1>sdalooh</h1>
    @endsection
